#'@title Cost function
#'
#'@author JWM Pullens, M Jabloun, D Nagy
#'
#'@description This function updates the parameters, runs the model with the new parameters and calculates the cost/fit.
#'
#'@param p Vector of parameter values that will be used to update the input files (names of parameters are in p.conifg)
#'@param p.config The parameter file in which the names of the parameters that need to be changed are located.
#'@param RunFile The complete path to the file with extension ".dai". This file is the setup file of the model.
#'@param showLogFile Either True or False to show the log file. (default = FALSE)
#'@param PathToDaisy Specify the path to the Daisy executable
#'@param DEoptim Specify if you run Daisy for DEOptim
#'@param Morris Specify if you run Daisy for Morris
#'@param dflt Specify if you run Daisy for default values
#'@param costfunction read.optim (needs explination)
#'@param obs  Observation against which the simulation needs to be tested.
#'@param wdDir working environment path
#'@param OutDir  output path
#'@param interval is the interval of the calibration period, in our case the from 1992 and 1993 drainage year.
#'@param year if is TRUE than user gets the all output objectives of the years, if it FALSE, it gives the mean of all calculated annual objective.
#'@param ind index
#'@param All If TRUE Giving all performance measure, if FALSE giving the specified performance measure in the script
#'
#'@examples
#'\dontrun{
#'f.cost(p,costfunction, p.config, obs, sim.file,RunFile,PathToDaisy)
#'}
#' @export

f.cost <- function(p, p.config, RunFile,showLogFile,PathToDaisy,Morris,DEoptim,dflt,costfunction,obs,wdDir,OutDir,interval,year,All,ind) {
  #1. use new parameters generated by the optim algorithm
  obs=obs
  wdDir=wdDir
  OutDir=OutDir
  interval=interval
  year=year
  All=All
  ind=ind
  
  updateParameters(p, p.config,RunFile, Morris, DEoptim,dflt, ind)
  #2. Run Daisy with the new input files
  runDaisy(p.config,RunFile,showLogFile ,PathToDaisy, Morris=F,DEoptim=F,dflt=F,costfunction=NULL,obs,wdDir,OutDir,interval=NULL,year=F,All=F,ind=NULL)
}