#'@title Cost function
#'
#'@author JWM Pullens, M Jabloun
#'
#'@description This function updates the parameters, runs the model with the new parameters and calculates the cost/fit.
#'
#'@param p Vector of parameter values that will be used to update the input files (names of parameters are in p.conifg)
#'@param costfunction Is the cost function. The used cost function is user defined and has to be defined as: f.cost(obs,sim.file)
#'@param p.config The parameter file in which the names of the parameters that need to be changed are located.
#'@param obs Observation against which the simulation needs to be tested.
#'@param RunFile The complete path to the file with extension ".dai". This file is the setup file of the model.
#'@param PathToDaisy Specify the path to the Daisy executable
#'@param DEO Specify if you run Daisy for DEOptim
#'@param ... addtional parameters
#'
#'@examples
#'\dontrun{
#'f.cost(p,costfunction, p.config, obs, sim.file,RunFile,PathToDaisy)
#'}
#' @export

f.cost <- function(p,costfunction, p.config, obs, RunFile,PathToDaisy,DEO=F,...) {
  #1. use new parameters generated by the optim algorithm

  updateParameters(p, p.config,DEO)
  #2. Run Daisy with the new input files
  runDaisy(RunFile=RunFile,showLogFile =  FALSE,PathToDaisy = PathToDaisy)
  #3. calculate the objective function
  costfunction(obs,...)
}
