#'@title Optimising function
#'
#'@author JWM Pullens, M Jabloun
#'
#'@description This function combines UpdateParameters, RunDaisy and the f.cost function. This function can be run if an optimization is needed.
#'
#'@param p Parameter
#'@param f.cost User defined cost function
#'@param RunFile The complete path to the file with extension ".dai". This file is the setup file of the model.
#'@param p.config The parameter file
#'@param obs Observation against which the simulation needs to be tested.
#'@param sim.file Simulation against which the measured data needs to be tested.
#'@param PathToDaisy Specify the path to the Daisy executable
#'
#'@examples
#'\dontrun{
#'f.optim (p, f.cost, RunFile, p.config, obs, sim.file,PathToDaisy)
#'}
#' @export

f.optim <- function(p, f.cost, RunFile, p.config, obs, sim.file,PathToDaisy) {
  #1. use new parameters generated by the optim algorithm
  updateParameters(p, p.config)
  #2. Run Daisy with the new input files
  runDaisy(RunFile, TRUE,PathToDaisy)
  #3. calculate the objective function
  f.cost(obs, sim.file)
}
