#'@title Optimizing parameters
#'
#'@author JWM Pullens, M Jabloun
#'
#'@description This function updates the parameters, rund the model with the new parameters and calculates the cost/fit.
#'
#'@param p Name of the parameter
#'@param p.config The parameter file
#'@param obs Observation against which the simulation needs to be tested.
#'@param sim.file Simulation against which the measured data needs to be tested.
#'@param f.cost Is the cost function. The used cost function is user defined and has to be defined as: f.cost(obs,sim.file)
#'
#'
#'@examples
#'\dontrun{
#'updateParameters(p= "", p.config="")
#'}
#' @export


f.optim <- function(p, p.config, obs, sim.file,f.cost) {
  #1. use new parameters generated by the optim algorithm
  updateParameters(p, p.config)
  #2. Run Daisy with the new input files
  runDaisy(p.config$to.file, FALSE)
  #3. calculate the objective function
  f.cost(obs, sim.file)
}
